version: '3'

services:
  mt5:
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    environment:
      - CUSTOM_USER=Bagshaw
      - PASSWORD=Ibisobia007@

vps:
  build: .
  port:
    - "80:80"
  depends_on:
    - mt5


    
      

